# Generated by Django 5.2.7 on 2025-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='audio',
            field=models.FileField(null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='students',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='students',
            name='document',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile_Number',
            field=models.IntegerField(null=True),
        ),
    ]
