from django.shortcuts import render,redirect
from django.http import HttpResponse
import json
import csv
import zipfile
import io
# Create your views here.

def text_response1(req):
    return HttpResponse("Welcome to Django!")
    
def html_response(request):
 html = "<h1>Welcome to My Django Site</h1><p>This is HTML content.</p>"
 return HttpResponse(html, content_type="text/html")

def json_response(request):
 data = {"name": "Neeraj", "role": "Developer"}
 json_data = json.dumps(data)
 return HttpResponse(json_data,content_type="application/json")



def download_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="employees.csv"'
    writer = csv.writer(response)
    writer.writerow(['Name', 'Department', 'Salary'])
    writer.writerow(['Neeraj', 'IT', 50000])
    writer.writerow(['Ravi', 'HR', 40000])
    return response

def download_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # Example content (real projects use ReportLab or WeasyPrint)
    response.write("This is a dummy PDF content.")
    return response


 
def download_zip(request):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w') as zip_file:
        zip_file.writestr('hello.txt', 'This is inside the ZIP file.')
        zip_file.writestr('readme.txt', 'Generated by Django!')
    response = HttpResponse(buffer.getvalue(), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename="files.zip"'
    return response

def css_response(request):
    css_content = """
    body {
        background-color: #f0f0f0;
        font-family: Arial, sans-serif;
    }
    h1 {
        color: blue;
        text-align: center;
    }
    """
    return HttpResponse(css_content, content_type="text/css")



def jpeg_image_response(request):
    with open("static/images/sample.jpg", "rb") as img:
        return HttpResponse(img.read(), content_type="image/jpeg")
    
    
    
def png_image_response(request):
    with open("static/images/logo.png", "rb") as img:
        return HttpResponse(img.read(), content_type="image/png")
    
    
    
def download_image(request):
    with open("static/images/logo.png", "rb") as img:
        response = HttpResponse(img.read(), content_type="image/png")
        response['Content-Disposition'] = 'attachment; filename="logo.png"'
        return response
    

def audio_response(request):
    with open("static/audio/sample.mp3", "rb") as audio_file:
        return HttpResponse(audio_file.read(), content_type="audio/mpeg")
    
    
def download_audio(request):
    with open("static/audio/sample.mp3", "rb") as audio_file:
        response = HttpResponse(audio_file.read(), content_type="audio/mpeg")
        response['Content-Disposition'] = 'attachment; filename="sample.mp3"'
        return response
    
    
def video_response(request):
    with open("static/videos/demo.mp4", "rb") as video_file:
        return HttpResponse(video_file.read(), content_type="video/mp4")
    
    
    
def download_video(request):
    with open("static/videos/demo.mp4", "rb") as video_file:
        response = HttpResponse(video_file.read(), content_type="video/mp4")
        response['Content-Disposition'] = 'attachment; filename="demo.mp4"'
        return response