# Generated by Django 5.2.8 on 2025-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
